// src/components/projects/ProjectCard.tsx
import { FaCode, FaWindowMaximize } from "react-icons/fa";

interface Props {
  title: string;
  description: string;
  image?: string;
  repo?: string;
  link?: string;
}

const hover =
  'hover:text-orange-500 hover:dark:text-teal-500 transition-colors';

function ProjectCard({ title, description, repo, image, link }: Props) {
  return <div className="flex flex-col">
    {image ?
      <img
        src={image}
        alt={title}
        className="border-[1px] border-black/30 dark:border-white/30 w-full aspect-[16/9] rounded-lg shadow-md shadow-orange-500 dark:shadow-teal-500 hover:scale-[1.05] transition-all"
      />
      : <div
        className="border-[1px] border-black/30 dark:border-white/30 w-full aspect-[16/9] rounded-lg hover:scale-[1.03] transition-all"
      />}
    <div className="flex items-center justify-between pt-6 pb-2">
      <a href={link} className={`text-xl font-bold ${hover}`}>{title}</a>
      <div className="gap-4 flex text-xl">
        {repo && <a href={repo}>
          <FaCode className={hover} />
        </a>}
        {link && <a href={link}>
          <FaWindowMaximize className={hover} />
        </a>}
      </div>
    </div>
    <p className="font-sm text-black/50 dark:text-white/50">{description}</p>
  </div>
}

export default ProjectCard

// src/components/projects/ProjectCard.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';

  export let title: string;
  export let description: string;
  export let image: string = '';
  export let repo: string = '';
  export let link: string = '';

  const hover =
    'hover:text-orange-500 hover:dark:text-teal-500 transition-colors hover:scale-[1.1]';
</script>

<div class="flex flex-col">
  {#if image}
    <img
      src={image}
      alt={title}
      class="border-[1px] border-black/30 dark:border-white/30 w-full aspect-[16/9] rounded-lg shadow-md shadow-orange-500 dark:shadow-teal-500 hover:scale-[1.05] transition-all"
    />
  {:else}
    <div
      class="border-[1px] border-black/30 dark:border-white/30 w-full aspect-[16/9] rounded-lg hover:scale-[1.03] transition-all"
    />
  {/if}
  <div class="flex items-center justify-between pt-6 pb-2">
    <a href={link} class={`text-xl font-bold ${hover}`}>{title}</a>
    <div class="gap-4 flex text-xl">
      {#if repo}<a href={repo} class={hover}>
          <Icon icon="fa6-solid:code" />
        </a>
      {/if}
      {#if link}<a href={link} class={hover}>
          <Icon icon="fa6-solid:window-maximize" />
        </a>
      {/if}
    </div>
  </div>
  <p class="font-sm text-black/50 dark:text-white/50">{description}</p>
</div>
