// src/layouts/ThemeSwitcher.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';
  import { onMount } from 'svelte';

  let theme = localStorage.getItem('theme') || 'light';
  let isMounted = false;

  const toggle = () => {
    if (theme === 'light') theme = 'dark';
    else theme = 'light';
  };

  onMount(() => {
    isMounted = true;
  });

  $: {
    if (isMounted) {
      if (theme === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
      localStorage.setItem('theme', theme);
    }
  }
</script>

<button on:click={toggle} class="w-6 text-right">
  <Icon
    icon={!isMounted || theme === 'light' ? 'fa6-solid:sun' : 'fa6-solid:moon'}
    class="hover:text-orange-500 hover:dark:text-teal-500 transition-colors"
  />
</button>

// src/layouts/ThemeSwitcher.tsx
import { useState, useEffect } from "react";
import { FaMoon, FaSun } from "react-icons/fa";

function ThemeSwitch() {
  const [theme, setTheme] = useState(localStorage.getItem('theme') || 'light');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);
  
  const toggle = () => {
    setTheme(theme === "light" ? "dark" : "light");
  }

  useEffect(() => {
    if (!isMounted) return;
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", theme);
  }, [theme, isMounted]);

  const getIcon = () => {
    if (theme === "light") return <FaSun className="hover:text-orange-500 transition-colors" />;
    else return <FaMoon className="hover:text-teal-500 transition-colors" />
  }

  return <button onClick={toggle} className="w-6 text-right">
    {(!isMounted || theme === "light")
      ? <FaSun className="hover:text-orange-500 transition-colors" />
      : <FaMoon className="hover:text-teal-500 transition-colors" />}
  </button>
};

export default ThemeSwitch;
